name: conditionam workflow
on: [push]
jobs:
  hello_world:
    if: github.repository == 'achalvats/github_workflow_practice'
    runs-on: ubuntu-latest
    steps:
      - name: 'Hello World'
        run: echo "Hey, how are you"
  goodbye_moon:
    runs-on: ubuntu-latest
    steps:
      - name: 'Goodbye Moon'
        run: echo "Bye Bye"
