name: "webhook event example"

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  respond-to-dispatch-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Print event details
        run: |
          echo "Triggered by event: ${{ github.event.action }}"
          echo "Full payload:"
          echo '${{ toJson(github.event) }}'
